stages:
  ingest:
    cmd: >
      PYTHONPATH=. python data/ingest.py
      --ticker ${data.ticker}
      --start ${data.start}
      --end ${data.end}
      --output ${data.output}
    deps:
      - data/ingest.py
    outs:
      - ${data.output}
    params:
      - data

  feature_engineering:
    cmd: >
      PYTHONPATH=. python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - ${data.output}
      - pyproject.toml
    outs:
      - data/raw/stock_features.csv
      - models/scaler_features.joblib
      - models/pca_features.joblib
    metrics:
      - reports/pca_explained_variance.csv:
          cache: false
    plots:
      - reports/correlation_matrix.csv:
          cache: false
      - reports/vif_report.csv:
          cache: false
      - reports/selected_features.csv:
          cache: false
    params:
      - data.output

  train:
    cmd: >
      PYTHONPATH=. python src/models/train.py
      --ticker ${train.ticker}
      --start ${train.start}
      --end ${train.end}
      --janela ${train.janela}
      --epochs ${train.epochs}
      --batch ${train.batch}
      --keras
    deps:
      - src/models/train.py
      - src/features/feature_engineering.py
      - data/raw/stock_features.csv
      - models/scaler_features.joblib
      - models/pca_features.joblib
      - pyproject.toml
    outs:
      - ${baseline.modelo_pytorch}
      - ${baseline.modelo_sklearn}
      - ${baseline.modelo_keras}
      - mlflow/mlflow.db
    params:
      - train
      - baseline.modelo_pytorch
      - baseline.modelo_sklearn
      - baseline.modelo_keras

  baseline:
    cmd: >
      PYTHONPATH=. python src/models/baseline.py
      --ticker ${baseline.ticker}
      --start ${baseline.start}
      --end ${baseline.end}
      --janela ${train.janela}
      --modelo-pytorch ${baseline.modelo_pytorch}
      --modelo-sklearn ${baseline.modelo_sklearn}
      --modelo ${baseline.modelo_keras}
      --keras
    deps:
      - src/models/baseline.py
      - data/raw/stock_features.csv
      - ${baseline.modelo_pytorch}
      - ${baseline.modelo_sklearn}
      - ${baseline.modelo_keras}
      - pyproject.toml
    outs:
      - reports/metrics_comparison.csv
      - reports/model_predictions_comparison.png
    metrics:
      - reports/metrics.json:
          cache: false
    params:
      - baseline
      - train.janela

  plots:
    cmd: >
      PYTHONPATH=. python src/utils/plot_metrics.py
    deps:
      - src/utils/plot_metrics.py
      - reports/metrics.json
    outs:
      - reports/comparacao_modelos.png
      - reports/ranking_mae.png
      - reports/mape.png