data:
  ticker: ITUB4.SA
  start: "2025-04-01"
  end: "2027-04-30"
  output: data/raw/stock_data.csv

features:
  input: data/raw/stock_data.csv
  output: data/raw/stock_features.csv
  scaler: models/scaler_features.joblib
  pca: models/pca_features.joblib

train:
  ticker: ITUB4.SA
  start: "2025-04-01"
  end: "2027-04-30"
  janela: 90
  epochs: 40
  batch: 32

baseline:
  ticker: ITUB4.SA
  start: "2025-04-01"
  end: "2027-04-30"
  modelo_pytorch: models/modelo_ITUB4.SA_pytorch.pth
  modelo_sklearn: models/modelo_ITUB4.SA_sklearn.joblib
  modelo_keras: models/modelo_ITUB4.SA.keras